version: '3.7'

services:

  taipy:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    networks:
      - taipy-network
    expose:
      - "5000"
    tty: true
    volumes:
      - .:/app

networks:
  taipy-network:
