site_name: Taipy
# site_url: http://www.avaiga.com
repo_url: https://github.com/avaiga/taipy
repo_name: taipy
#strict: true
copyright: 2021 Avaiga
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Modules: api.md
  - Contributing: contributing.md
  - Authors: authors.md
  - History: history.md
theme:
  name: material
  language: en
  custom_dir: tools/mkdocs
  logo: assets/images/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
#293183
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
extra_css:
  - assets/stylesheets/avaiga.css
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - meta
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      watch:
        - taipy
extra:
  social:
    - icon: fontawesome/brands/twitter
      # replace with your own tweet link below
      link: http://www.avaiga.com
      name: Tweet
    - icon: fontawesome/brands/facebook
      # replace with your own facebook link below
      link: http://www.avaiga.com
      name: Facebook
    - icon: fontawesome/brands/github
      link: https://github.com/avaiga/taipy
      name: Github
    - icon: material/email
      link: "mailto:taipy.dev@avaiga.com"
  # to enable disqus, uncomment the following and put your disqus id below
  # disqus: disqus_id
  generator: false
# uncomment the following and put your google tracking id below to enable GA
#google_analytics:
  #- UA-xxx
  #- auto
