site_name: Taipy
# site_url: http://www.avaiga.com
repo_url: https://github.com/avaiga/taipy
repo_name: taipy
#strict: true
copyright: © 2022 Avaiga
nav:
  - Home: index.md
  - 'Getting started': 
    - 'Installation': 'getting_started/installation.md'
    - 'Creating a Taipy application': 'getting_started/creating_a_taipy_application.md'
  - 'Manuals':
    - 'About Taipy user manuals': 'manuals/about.md'
    - 'Scenario management': 'manuals/scenario_management.md'
    - Graphical User Interface: 
        - 'About': 'manuals/gui/user.md'
        - 'Pages': 'manuals/gui/user_pages.md'
        - 'Controls': 'manuals/gui/user_controls.md'
        - 'Binding variables': 'manuals/gui/user_binding.md'
        - 'Styling': 'manuals/gui/user_styling.md'
        - 'Callbacks': 'manuals/gui/user_callbacks.md'
        - 'Dialogs': 'manuals/gui/user_dialogs.md'
        - 'Notifications': 'manuals/gui/user_notifications.md'
        - 'GUI References': 'manuals/gui/user_gui.md'
    - 'References': 'manuals/reference.md'
  - 'Contributing':
    - 'About contributions': 'contributing/about_contributing.md'
    - 'How you can contribute': 'contributing/how-to-contribute.md'
    - 'Get started for local development': 'contributing/get-started.md'
  - 'Credits':
    - 'Development lead': 'credits/development_lead.md'
    - 'Contributors': 'credits/contributors.md'
  - 'History': 'history.md'
theme:
  name: material
  language: en
  custom_dir: tools/mkdocs
  logo: assets/images/logo.png
  font:
    text: Lato
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: indigo
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: deep-orange
      accent: deep-orange
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
    - content.tabs.link
extra_css:
  - assets/stylesheets/avaiga.css
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - meta
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: false
      watch:
        - taipy
  - macros:
      module_name: tools/mkdocs/postprocess
extra:
  social:
    - icon: fontawesome/brands/twitter
      # replace with your own tweet link below
      link: http://www.avaiga.com
      name: Tweet
    - icon: fontawesome/brands/facebook
      # replace with your own facebook link below
      link: http://www.avaiga.com
      name: Facebook
    - icon: fontawesome/brands/github
      link: https://github.com/avaiga/taipy
      name: Github
    - icon: material/email
      link: "mailto:taipy.dev@avaiga.com"
  # to enable disqus, uncomment the following and put your disqus id below
  # disqus: disqus_id
  generator: false
# uncomment the following and put your google tracking id below to enable GA
#google_analytics:
  #- UA-xxx
  #- auto