"""Taipy Graphical User Interface generator.

The Taipy Gui package provides User Interface generation based on
page templates.

The pages are generated by a Web server that allows Web clients to
connect, display and interact with the page content through visual
elements.

Here is how you can create your first Taipy User Interface:

   - Create a Python source file.
     Copy these two lines into a file called _taipy.py_.
     ```py
     from taipy import Gui
     Gui("# Hello Taipy!").run()
     ```
   - Install Taipy:
     ```
     pip install taipy
     ```
   - Run your application:
     ```
     python taipy.py
     ```

Your browser opens a new page, showing the content of your graphical
application.
"""

from .gui import Gui

__author__ = """Avaiga"""
__email__ = "taipy.dev@avaiga.com"
__version__ = "1.0.0.dev"
