name: 'code-coverage'
on:
    pull_request:
        branches: [ master,main,release ]

    workflow_dispatch:
jobs:
    code-coverage:
        runs-on: ubuntu-18.04
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up Python 3.9
                uses: actions/setup-python@v2
                with:
                    python-version: 3.9

            -   name: Install pipenv
                run: |
                    python -m pip install --upgrade pipenv wheel
                    pip install pytest pytest-cov

            -   id: cache-pipenv
                uses: actions/cache@v1
                with:
                    path: ~/.local/share/virtualenvs
                    key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

            -   name: Install dependencies
                run: |
                    pipenv lock
                    pipenv install --system --dev --python 3.9

            -   name: Build coverage file
                run: |
                    pytest -s --cov=taipy --cov-append --cov-report=xml --cov-report term-missing tests

            -   name: Code coverage
                uses: orgoro/coverage@v2
                with:
                    coverageFile: coverage.xml
                    token: ${{ secrets.GITHUB_TOKEN }}
                    thresholdAll: 0.85
