# This is a basic workflow to help you get started with Actions

name: dev workflow

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master,main,release ]
  pull_request:
    branches: [ master,main,release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    strategy:
      matrix:
        python-versions: [3.9]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
          pip install pytest pytest-cov tox tox-gh-actions

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev
      - id: code-quality
        uses: ricardochaves/python-lint@v1.4.0
        with:
            python-root-list: "taipy tests"
            use-pylint: false
            use-isort: false
            extra-pycodestyle-options: "--max-line-length=88 --ignore=E203,E266,E501,E722,W503,F403,F401"
            extra-mypy-options: "--ignore-missing-imports"
      - name: test with tox
        run:
          tox

      - name: list files
        run: ls -l .
