name: release workflow

on:
  push:
    branches:
      - 'release/**'

jobs:
  build:
    name: Build Gui React Frontend

    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-18.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: npm build ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Gui Dependencies
        working-directory: ./gui
        run: npm ci

      - name: Build Gui React
        working-directory: ./gui
        run: npm run build

      - name: Remove .gitignore
        working-directory: ./taipy/gui
        run: rm -f .gitignore

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'React Build for Frontend'
          add: './taipy/gui'

  release:
    name: Release Taipy Package

    needs: build

    strategy:
      matrix:
        os: [ubuntu-18.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - run: git pull

      - name: Extract branch tag
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/heads/release/})"
        id: extract_branch

      - name: Extract commit hash
        shell: bash
        run: echo "##[set-output name=hash;]$(echo $(git rev-parse HEAD))"
        id: extract_hash

      - name: Create/update release and tag
        run: |
            gh release view ${{ steps.extract_branch.outputs.tag }} &&
            gh release delete ${{ steps.extract_branch.outputs.tag }} &&
            git tag -f ${{ steps.extract_branch.outputs.tag }} &&
            git push -f origin ${{ steps.extract_branch.outputs.tag }};
            gh release create ${{ steps.extract_branch.outputs.tag }} --target ${{ steps.extract_hash.outputs.hash }} --notes "Release created using Github Workflows"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
