name: Create Github Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The release/package version to create (ex: 1.0.0)"
        required: true

jobs:
  test-package:
    timeout-minutes: 20
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install npm
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Ensure package version is properly set
        run: |
          echo 'version="${{ github.event.inputs.version }}"' | grep -f - setup.py

      - name: Validate branch name
        run: |
          echo """
          import re, sys
          setup = open('setup.py').read()
          x = re.search(r'version=\"(\d+)\.(\d+)\.(\d+)(?:\.([a-zA-Z0-9_]+))?\"', setup)
          if not x:
              raise ValueError('Invalid version expression')
          if f'release/{x.group(1)}.{x.group(2)}' != sys.argv[1]:
              raise ValueError('Branch name mismatch')
          """ > /tmp/check.py
          python /tmp/check.py "${{ steps.extract_branch.outputs.branch }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build and test the package
        run: |
          python setup.py build_py && python -m build
          rm -rf src
          pip install dist/*.tar.gz
          pip install pytest pytest-mock pytest-playwright pytest-timeout testbook
          pip install ipython ipykernel
          ipython kernel install --name "python3" --user
          playwright install chromium
          pytest

  release:
    needs: [test-package]
    timeout-minutes: 20
    name: Release package
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Extract commit hash
        shell: bash
        run: echo "##[set-output name=hash;]$(echo $(git rev-parse HEAD))"
        id: extract_hash

      - name: Create/update release and tag
        run: |
            gh release create ${{ github.event.inputs.version }} --target ${{ steps.extract_hash.outputs.hash }} --notes "Release created using Github Workflows"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
